services:
  jenkins:
#    image: jenkins/jenkins:lts-jdk11
    image: jenkins-docker-local
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      # JAVA_OPTS: "-Duser.timezone=Asia/Seoul -Djenkins.install.runSetupWizard=false"
