services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      TZ: "Asia/Seoul"
      JAVA_OPTS: "-Duser.timezone=Asia/Seoul"
      # JAVA_OPTS: "-Duser.timezone=Asia/Seoul -Djenkins.install.runSetupWizard=false"
